
import 'dart:convert';
import 'dart:io';
import 'lib/src/screen/list_url.dart';

void main() {
  final Map<String, dynamic> allData = {
    'belts': belts,
    'gloves': gloves,
    'hairAccessories': hairAccessories,
    'hats': hats,
    'jewelry': jewelry,
    'scarves': scarves,
    'sunglasses': sunglasses,
    'watches': watches,
    'backpacks': backpacks,
    'clutches': clutches,
    'handbags': handbags,
    'messengerBags': messengerBags,
    'toteBags': toteBags,
    'travelBags': travelBags,
    'wallets': wallets,
    'activewear': activewear,
    'blouses': blouses,
    'cardigans': cardigans,
    'coats': coats,
    'dresses': dresses,
    'girlCollection': girlCollection,
    'hoodies': hoodies,
    'jackets': jackets,
    'jeans': jeans,
    'joggers': joggers,
    'leggings': leggings,
    'pants': pants,
    'polos': polos,
    'shirts': shirts,
    'shorts': shorts,
    'skirt': skirt,
    'suits': suits,
    'sweatshirts': sweatshirts,
    'tShirts': tShirts,
    'shoesBoots': shoesBoots,
    'flats': flats,
    'heeled': heeled,
    'loafers': loafers,
    'sandals': sandals,
    'slippers': slippers,
    'sneakers': sneakers,
    'sportsShoes': sportsShoes,
    'bags': bags,
    'clothes': clothes,
    'gift': gift,
    'lingerie': lingerie,
    'shoes': shoes,
    'accessories': accessories,
    'toys': toys,
    'watch': watch,
    'bodysuitProduct': bodysuitProduct,
    'perfumesData': perfumesData,
    'nightwearProducts': nightwearProducts,
    'braProducts': braProducts,
    'pantyProducts': pantyProducts,
    'shapewearProducts': shapewearProducts,
    'sockProducts': sockProducts,
    'tightsProducts': tightsProducts,
    'discoverProducts': discoverProducts,
    'allItems': allItems,
    'recentlyViewedImages': recentlyViewedImages,
    'wishlistItems': wishlistItems,
    'products': products,
    'justForYouData': justForYouData,
    'popularItems': popularItems,
    'flashSaleImages': flashSaleImages,
    'bannerData': bannerData,
    'brandData': brandData,
    'cosmeticsData': cosmeticsData,
    'birthdayGift': birthdayGift,
    'anniversaryGift': anniversaryGift,
    'weddingGift': weddingGift,
    'babyGift': babyGift,
    'valentineGift': valentineGift,
    'graduationGift': graduationGift,
    'personalizedGift': personalizedGift,
    'skincare': skincare,
  };

  const JsonEncoder encoder = JsonEncoder.withIndent('  ');
  final String jsonString = encoder.convert(allData);

  final File file = File('all_data.json');
  file.writeAsStringSync(jsonString);

  print('Successfully exported all data to all_data.json');
}
